const $=id=>document.getElementById(id);
let token='',session='',sequence=0,current='',sources=[],briefings=[],activeBriefing=null,parentSource=null;
function el(tag,value,css){const e=document.createElement(tag);if(value!==undefined)e.textContent=value;if(css)e.className=css;return e}
async function rpc(method,params={},notification=false){const body={jsonrpc:'2.0',method,params};if(!notification)body.id=++sequence;const headers={'Content-Type':'application/json',Accept:'application/json, text/event-stream',Authorization:'Bearer '+token,'MCP-Protocol-Version':'2025-11-25'};if(session)headers['MCP-Session-Id']=session;const r=await authenticatedFetch('/mcp',{method:'POST',headers,body:JSON.stringify(body)});session=r.headers.get('MCP-Session-Id')||session;if(r.status===202)return {};const data=await r.json();if(!r.ok||data.error)throw Error(data.error?.message||data.error||'MCP request failed');return data.result}
async function tool(name,args){const r=await rpc('tools/call',{name,arguments:args});if(r.isError)throw Error(r.content[0].text);return r.structuredContent}
let clearTrailBusy=false;
for(const eventName of ['click','keydown','submit'])document.addEventListener(eventName,event=>{if(clearTrailBusy){event.preventDefault();event.stopImmediatePropagation()}},true);
async function busy(message,fn){
 if(clearTrailBusy)return;clearTrailBusy=true;document.body.setAttribute('aria-busy','true');
 $('status').textContent=message;$('workingActivity').hidden=false;$('activityText').textContent=message;
 document.querySelectorAll('.dialog-error').forEach(e=>e.remove());
 try{await fn()}catch(e){$('status').textContent=e.message;const dialog=document.querySelector('dialog[open]');if(dialog){const error=el('p',e.message,'dialog-error');error.setAttribute('role','alert');const actions=dialog.querySelector('.actions');if(actions)actions.before(error);else dialog.append(error)}}
 finally{clearTrailBusy=false;document.body.setAttribute('aria-busy','false');$('workingActivity').hidden=true}
}

async function projects(){const data=await tool('list_projects',{});$('project').replaceChildren();if(!data.projects.length){$('project').append(el('option','Create a project to begin'));current='';return}data.projects.forEach(p=>{const o=el('option',p.name);o.value=p.id;$('project').append(o)});if(!data.projects.some(p=>p.id===current))current=data.projects[0].id;$('project').value=current}
async function refresh(){if(!current){sources=[];briefings=[];activeBriefing=null;updatePath();await restoreConversation();return;}localStorage.setItem('cleartrail-project',current);sources=(await tool('list_sources',{project_id:current})).sources;briefings=(await tool('list_briefings',{project_id:current})).briefings;renderSources();updatePath();await restoreConversation();$('matches').replaceChildren();$('older').hidden=!briefings.length;$('history').replaceChildren();briefings.forEach(b=>{const button=el('button',b.title+' · '+new Date(b.created_at).toLocaleString(),'quiet');button.onclick=()=>showBriefing(b);$('history').append(button)});if(briefings.length)showBriefing(briefings[0]);else{activeBriefing=null;renderDashboard();$('export').hidden=true;$('followups').replaceChildren();$('answer').replaceChildren(el('div','Add sources, then ask a question. Your saved briefings return when you reopen this project.','empty'))}}
function renderSources(){$('sources').replaceChildren();sources.forEach(s=>{const card=el('article',undefined,'source '+s.kind);card.append(el('h3',s.title),el('span',s.kind,'pill'),el('div',s.document_key+' / '+s.revision,'meta'));const row=el('div',undefined,'row');const view=el('button','Read source','quiet');view.onclick=()=>openEvidence(s.id);const revision=el('button','Add revision','quiet');revision.onclick=()=>sourceForm(s);row.append(view,revision);if(s.parent_source_id){const compare=el('button','Compare','quiet');compare.onclick=()=>busy('Comparing saved revisions…',async()=>{const d=await tool('compare_revisions',{project_id:current,before_id:s.parent_source_id,after_id:s.id});$('evidenceTitle').textContent='What changed';$('evidenceBody').textContent=d.authority_note+'\n\n'+d.diff;$('evidenceDialog').showModal();$('status').textContent='Exact text changes shown. Revision order does not establish approval.'});row.append(compare)}card.append(row);$('sources').append(card)})}
async function openEvidence(id,quote){await busy('Opening exact source…',async()=>{const s=(await tool('read_source',{project_id:current,source_id:id})).source;$('evidenceTitle').textContent=s.title+' / '+s.revision;$('evidenceBody').replaceChildren();if(quote&&s.text.includes(quote)){const offset=s.text.indexOf(quote);$('evidenceBody').append(document.createTextNode(s.text.slice(0,offset)),el('mark',quote),document.createTextNode(s.text.slice(offset+quote.length)))}else $('evidenceBody').textContent=s.text;$('evidenceDialog').showModal();$('status').textContent='Showing the saved revision, with its exact wording.'})}
function citation(c){const button=el('button','“'+c.quote+'”','citation');button.append(el('span',c.title+' / '+c.revision+' / '+(c.page?'page '+c.page:'line '+c.line)));button.onclick=()=>openEvidence(c.source_id,c.quote);return button}
function showBriefing(b){activeBriefing=b;renderDashboard();$('followups').replaceChildren();(b.next_questions||[]).forEach(q=>{const btn=el('button',q,'quiet');btn.onclick=()=>{$('question').value=q;$('ask').click()};$('followups').append(btn)});$('export').hidden=false;$('answer').replaceChildren(el('h2',b.title),el('p',b.question,'note'));if(b.source_count!==undefined){const stats=el('div',undefined,'review-stats');stats.append(el('span',b.source_count+' sources checked'),el('span',(b.comparisons||[]).length+' revision comparisons'),el('span',b.conflicts.length+' disagreements to review'));$('answer').append(stats)}if(b.source_snapshot_outdated){$('answer').append(el('p','Sources changed after this briefing. Prepare a fresh briefing for the current decision.','conflict'))}b.findings.forEach(f=>{const box=el('div',undefined,'finding');box.append(el('p',f.text));f.citations.forEach(c=>box.append(citation(c)));$('answer').append(box)});b.conflicts.forEach(f=>{const box=el('div',undefined,'conflict');box.append(el('h3',f.certainty==='possible'?'Possible disagreement to review':'Unresolved conflict'),el('p',f.text));f.citations.forEach(c=>box.append(citation(c)));$('answer').append(box)});if(b.unknowns.length){$('answer').append(el('h3','Still unknown'));b.unknowns.forEach(u=>$('answer').append(el('p',u)))}(b.comparisons||[]).forEach(c=>{const box=el('details',undefined,'comparison');box.append(el('summary',c.document_key+' · '+c.before+' → '+c.after),el('pre',c.diff));$('answer').append(box)});$('answer').append(el('p',b.interpretation_note,'note'),el('p','Saved '+new Date(b.created_at).toLocaleString()+' · '+b.model.name+' · '+b.model.elapsed_seconds+'s · '+b.tool_trace.length+' MCP reads','note'))}
function sourceForm(parent=null){if(!current){$('status').textContent='Create a project first.';return}parentSource=parent;$('sourceForm').reset();$('sourceHeading').textContent=parent?'Add a separate revision':'Add a source';$('title').value=parent?.title||'';$('documentKey').value=parent?.document_key||'';$('kind').value=parent?.kind||'notes';$('sourceDialog').showModal()}
function fileContent(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)})}
$('newProject').onclick=()=>{$('projectForm').reset();$('newDialog').showModal()};$('addSource').onclick=()=>sourceForm();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('projectForm').onsubmit=e=>{e.preventDefault();busy('Creating a separate evidence project…',async()=>{const p=await tool('create_project',{name:$('projectName').value});current=p.id;$('newDialog').close();await projects();await refresh();$('status').textContent='Project created. Add its first source.'})};
$('project').onchange=()=>busy('Opening saved project…',async()=>{current=$('project').value;await refresh();$('status').textContent='Project sources and saved briefings restored.'});
$('sourceForm').onsubmit=e=>{e.preventDefault();busy('Saving the original source and revision…',async()=>{const args={project_id:current,title:$('title').value,revision:$('revision').value,document_key:$('documentKey').value,kind:$('kind').value};if(parentSource)args.parent_source_id=parentSource.id;const file=$('sourceFile').files[0];if(file){args.filename=file.name;args.content_base64=await fileContent(file)}else args.text=$('sourceText').value;await tool('import_document',args);$('sourceDialog').close();await refresh();$('status').textContent='Source saved. Earlier revisions are preserved.'})};
$('search').onclick=()=>busy('Searching exact source lines…',async()=>{const d=await tool('search_evidence',{project_id:current,query:$('query').value});$('matches').replaceChildren();d.matches.forEach(m=>{const b=el('button',m.quote,'citation');b.append(el('span',m.title+' / '+m.revision+' / line '+m.line));b.onclick=()=>openEvidence(m.source_id,m.quote);$('matches').append(b)});$('status').textContent=d.total_matches+' matching lines found.'});
$('ask').onclick=()=>busy($('mode').value==='sarah'?'Sarah is preparing your reply…':'Reading evidence with the optional local model…',async()=>{const r=await authenticatedFetch('/api/ask',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({project_id:current,question:$('question').value,mode:$('mode').value})});const d=await r.json();if(!r.ok)throw Error(d.error);if(d.briefing){await refresh();showBriefing(d.briefing);$('status').textContent='Evidence checked. Your quotes and any open disagreements are below.';}else{await restoreConversation();$('status').textContent='Sarah replied. Keep talking, or add the evidence you want to review.';}queueSarahReply(d.spoken_reply||d.reply)});
$('export').onclick=()=>busy('Saving the briefing…',async()=>{const d=await tool('export_briefing',{project_id:current,briefing_id:activeBriefing.id});const url=URL.createObjectURL(new Blob([d.markdown],{type:'text/markdown;charset=utf-8'}));const a=el('a');a.href=url;a.download='ClearTrail-'+d.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('status').textContent='Markdown briefing exported with exact source quotes and snapshot hash.'});
$('sample').onclick=()=>busy('Creating an explicitly fictional example…',async()=>{const p=await tool('create_project',{name:'Fictional office move — conflicting dates'});current=p.id;const docs=[['June 3 decision','decision','DECISION RECORD — June 3\nMira approved moving the office on June 12.\nThe move must wait for facilities to approve the new office access.'],['June 6 proposal','proposal','PROPOSAL — June 6\nA June 11 move was suggested to avoid the busy delivery period.\nThis proposal is not approved. The June 3 decision remains in force until sign-off.'],['June 7 decision','decision','DECISION RECORD — June 7\nJonas approved moving the office on June 13.\nThis note does not state whether it replaces Mira\'s June 3 decision.']];let previous=null;for(const [revision,kind,text] of docs){const args={project_id:current,title:'Office move',document_key:'Move schedule',revision,kind,text};if(previous)args.parent_source_id=previous;previous=(await tool('import_document',args)).source.id}await projects();await refresh();$('question').value='What changed, and what is the current move decision? Explain the unresolved conflict without assuming the newest date wins.';$('status').textContent='Fictional example loaded. Ask for a briefing or compare the revisions.'});
(async()=>{await busy('Opening ClearTrail…',async()=>{const boot=await(await window.clearTrailBackend.fetch('/api/bootstrap')).json();token=boot.token;await rpc('initialize',{protocolVersion:'2025-11-25',capabilities:{},clientInfo:{name:'cleartrail-browser',version:'1.0.0'}});await rpc('notifications/initialized',{},true);current=localStorage.getItem('cleartrail-project')||'';await projects();await refresh();$('status').textContent='Sarah is ready. Ask, compare and export without an API key or an installed model.'})})();


async function localPost(path,payload){const r=await authenticatedFetch(path,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(payload)});if(!r.ok){let d=await r.json();throw Error(d.error||'Request failed')}return r}
async function restoreConversation(){const d=await(await localPost('/api/conversation',{project_id:current||null})).json();const box=$('conversation');box.replaceChildren();for(const entry of d.conversation.slice(-4)){box.append(el('div',entry.question,'chat-message owner'),el('div',entry.reply,'chat-message sarah'))}if(!d.conversation.length)box.append(el('div',"Hi, I'm Sarah. Tell me what you're working on, or ask where to start.",'chat-message sarah'));box.scrollTop=box.scrollHeight}
function updatePath(){$('sourceCount').textContent=sources.length;$('revisionCount').textContent=sources.filter(s=>s.parent_source_id).length;$('reviewCount').textContent=briefings.length;renderDashboard()}
$('saveMessage').onclick=()=>{if(!current){$('status').textContent='Create a project to keep this message as its first source.';$('newDialog').showModal();return}const message=$('question').value.trim();if(!message){$('status').textContent='Write the note you want to save first.';return}sourceForm();$('sourceText').value=message;$('kind').value='notes';$('title').value='Conversation note';$('documentKey').value='Conversation notes';$('revision').value=new Date().toISOString();$('sourceHeading').textContent='Review your message as evidence'};

async function authenticatedFetch(path,options){
  let r=await window.clearTrailBackend.fetch(path,options);
  // A 401 is rejected before execution; retrying it cannot duplicate a write.
  // Transport failures are not retried because a write may already have succeeded.
  if(r.status===401){
    const bootResponse=await window.clearTrailBackend.fetch('/api/bootstrap');
    if(!bootResponse.ok)throw Error('ClearTrail is restarting. Reopen the shortcut in a moment.');
    token=(await bootResponse.json()).token;session='';
    await rpc('initialize',{protocolVersion:'2025-11-25',capabilities:{},clientInfo:{name:'cleartrail-browser',version:'2.0.0'}});
    await rpc('notifications/initialized',{},true);
    const headers={...options.headers,Authorization:'Bearer '+token};
    if(path==='/mcp')headers['MCP-Session-Id']=session;
    r=await fetch(path,{...options,headers});
  }
  return r;
}
